name: Auto-Deploy Spring Boot

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build JAR with Maven
        run: ./mvnw clean package -DskipTests

      - name: Copy JAR to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: 163.245.207.8
          username: root
          key: ${{ secrets.VPS_PRIVATE_KEY }}
          source: "target/employee-management-0.0.1-SNAPSHOT.jar"
          target: "/root/employeeJava/Employee-Management/app.jar"

      - name: Restart Spring Boot service
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 163.245.207.8
          username: root
          key: ${{ secrets.VPS_PRIVATE_KEY }}
          script: sudo systemctl restart employee